name: POS API Automation
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman and Reporter
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Newman Tests
        # Using your exact filenames from the local terminal run
        run: |
          newman run "POS API TEST.postman_collection.json" \
          -e pos.postman_environment.json \
          -r cli,htmlextra \
          --reporter-htmlextra-export ./test-results/report.html

      - name: Upload HTML Report
        if: always() # Uploads even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: ./test-results/report.html
